var express = require("express");
var GlobalConfig = require("./config");
var loader = require("./load");
var fs = require("fs");
var app = new express();
app.use(express.static(GlobalConfig["pagepath"]));
app.post("/Login", loader.get("/Login"));
app.post("/GetMenu", loader.get("/GetMenu"));
app.post("/GetArticleList", loader.get("/GetArticleList"));
app.get("/GetFooter", loader.get("/GetFooter"));
app.post("/SetLike", loader.get("/SetLike"));
app.post("/SendEmail", loader.get("/SendEmail"));
app.post("/GetAllControl", loader.get("/GetAllControl"));
app.post("/GetFoot", loader.get("/GetFoot"));
app.get("/GetSubmenu", loader.get("/GetSubmenu"));
app.post("/GetPageTitle", loader.get("/GetPageTitle"));
app.get("/GetArticleCount", loader.get("/GetArticleCount"));
app.post("/GetSubtitle", loader.get("/GetSubtitle"));
app.post("/GetAllVideo", loader.get("/GetAllVideo"));
app.post("/GetFeatures", loader.get("/GetFeatures"));
app.post("/GetBenefits", loader.get("/GetBenefits"));
app.post("/WriterArticle", loader.get("/WriterArticle"));
app.post("/DeleteArticle", loader.get("/DeleteArticle"));
app.post("/GetArticleContent", loader.get("/GetArticleContent"));
app.post("/GetArticle", loader.get("/GetArticle"));
app.post("/ChangeArticle", loader.get("/ChangeArticle"));
app.post("/GetArticleLanguageType", loader.get("/GetArticleLanguageType"));
app.post("/WriteAritcleLanguage", loader.get("/WriteAritcleLanguage"));
app.get("/GetLanguage",loader.get("/GetLanguage"));
app.post("/GetDownLoadMessage",loader.get("/GetDownLoadMessage"));
app.get("/L",function(request,response){
    response.writeHead(200,"text/html");
    var file = fs.readFileSync("./page/login.html");
    response.write(file);
    response.end();
});
app.listen(GlobalConfig["port"]);